// <auto-generated />
using System;
using Main.Infrastructure.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Main.Infrastructure.Migrations
{
    [DbContext(typeof(IdentityAppDbContext))]
    [Migration("20260903002448_InitialCreateIdentity26")]
    partial class InitialCreateIdentity26
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Main.Model.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "00000003-0000-0000-0000-000000000000",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d7e235a3-ad67-4231-8993-071048db5b58",
                            Email = "admin@system.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAELaSZd75HLJFtBXs61OjlHn5t2QX+gcLEXgZB/UmtUf/qRktvLCco3vlMne7T8WgMA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2966a7ec-c5fe-48bb-8394-52a7dc025080",
                            TwoFactorEnabled = false,
                            UserName = "admin@system.com"
                        },
                        new
                        {
                            Id = "00000004-0000-0000-0000-000000000000",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e7b2ca18-78c9-4807-b2fe-968738cb905d",
                            Email = "tenant1.admin@test.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEPxRs+snHUvc+42ZES9H9xlMv9zXy3UmPsVHGdxVkUAb0KuvQ4JbTReB+5LG0hhhzA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2348d733-1bc0-440f-a9f9-5bc59889054c",
                            TwoFactorEnabled = false,
                            UserName = "tenant1.admin@test.com"
                        },
                        new
                        {
                            Id = "00000005-0000-0000-0000-000000000000",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "633d639a-7c85-4e1f-b345-702653b6ac22",
                            Email = "tenant1.manager@test.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAELDG04pqI7zhzjzTkwNGbBqAkHPyUqxgm2ZdNRziKfX619D7piF9NziaNMexv4H0rQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c72a9806-b3ca-4869-acc4-6ba1fe1234df",
                            TwoFactorEnabled = false,
                            UserName = "tenant1.manager@test.com"
                        },
                        new
                        {
                            Id = "00000006-0000-0000-0000-000000000000",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "795f250d-2b16-442f-a76f-f4fdadb68686",
                            Email = "tenant1.member@test.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEKYzuOJvPj6N3jcTuxR+WkZcKToiFdgpR8bHEUCJsGi9ZmLY0zfi79rY1ihCN0Z2gQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e67f4b85-c0a2-4381-89a3-cf9c2381eab4",
                            TwoFactorEnabled = false,
                            UserName = "tenant1.member@test.com"
                        },
                        new
                        {
                            Id = "00000007-0000-0000-0000-000000000000",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5241fe55-3930-4f5b-acb3-2ec9c7276de2",
                            Email = "tenant2.admin@test.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAELf9B5bohu33VlvouBi/DjW90PxLNffjiWhQfjlGR8ly/Z5MVyIQ1buQ/hpvMHLdww==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2943f3f8-ade2-4b17-8029-54e2555d525e",
                            TwoFactorEnabled = false,
                            UserName = "tenant2.admin@test.com"
                        },
                        new
                        {
                            Id = "00000008-0000-0000-0000-000000000000",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "efa4704f-afb3-4627-ac20-4194a4209e16",
                            Email = "tenant2.manager@test.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEOxGggJ9wWosKHVVEoELiMrA96YqCOmNfBm6hPuReOfjf0M5r58J+QQxjOVfYXksYg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2fb86047-e1aa-4b83-a90b-fb20f32d1c87",
                            TwoFactorEnabled = false,
                            UserName = "tenant2.manager@test.com"
                        },
                        new
                        {
                            Id = "00000009-0000-0000-0000-000000000000",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a25021ca-79f8-432e-a440-775160d9bae1",
                            Email = "tenant2.member@test.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEOOi1J5t604de513V7zDVs07BmkN6brGvWw9k5KbSjDnO55bzwiX+d0b1wF91Z6S8g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "89f2d250-3d74-4d9c-bd7f-ca1caf172d77",
                            TwoFactorEnabled = false,
                            UserName = "tenant2.member@test.com"
                        },
                        new
                        {
                            Id = "0000000a-0000-0000-0000-000000000000",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9038892e-bb93-45f5-b687-7dc944ab19fa",
                            Email = "finearts@test.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEBzAAkV+XTQyrUdn2lBq25B5JglK0qqHwVXhtEvvzxSPI17CcwSvskNYwyTzCCfogA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "603f4e87-1413-4c45-aa19-2b034628b57e",
                            TwoFactorEnabled = false,
                            UserName = "finearts@test.com"
                        },
                        new
                        {
                            Id = "0000000b-0000-0000-0000-000000000000",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fee6fd6c-89a4-490d-8328-dd04476583c8",
                            Email = "lifestyles@test.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEP58OGxCJkXrMoZj/bFUmCRBeJrneZNU2rt3XxkU3PtmTJMnM+Kv4v0HYAyXhO/DOg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "500bef51-0171-4cda-ba4a-4e4fdaf753fa",
                            TwoFactorEnabled = false,
                            UserName = "lifestyles@test.com"
                        });
                });

            modelBuilder.Entity("Main.Model.Identity.EmailOutboxMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CreatedOnUtc")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReceiverEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RetryCount")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenantContinent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TenantCountry")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("EmailOutboxMessages");
                });

            modelBuilder.Entity("Main.Model.Identity.Tenant", b =>
                {
                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HostType")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecretKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StoreType")
                        .HasColumnType("int");

                    b.Property<string>("TenantContinent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TenantCountry")
                        .HasColumnType("int");

                    b.Property<string>("TenantName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TenantId");

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            TenantId = new Guid("00000001-0000-0000-0000-000000000000"),
                            Host = "tenant1",
                            HostType = 1,
                            IsActive = true,
                            StoreType = 6,
                            TenantContinent = "Asia",
                            TenantCountry = 1,
                            TenantName = "Tenant 1 (Finearts: Collections)"
                        },
                        new
                        {
                            TenantId = new Guid("00000002-0000-0000-0000-000000000000"),
                            Host = "tenant2",
                            HostType = 1,
                            IsActive = true,
                            StoreType = 5,
                            TenantContinent = "Asia",
                            TenantCountry = 1,
                            TenantName = "Tenant 2 (Finearts: Crafts)"
                        },
                        new
                        {
                            TenantId = new Guid("00000011-0000-0000-0000-000000000000"),
                            Host = "finearts",
                            HostType = 1,
                            IsActive = true,
                            StoreType = 2,
                            TenantContinent = "Asia",
                            TenantCountry = 1,
                            TenantName = "Tenant 3 (Finearts: Arts)"
                        },
                        new
                        {
                            TenantId = new Guid("00000012-0000-0000-0000-000000000000"),
                            Host = "lifestyles",
                            HostType = 1,
                            IsActive = true,
                            StoreType = 1,
                            TenantContinent = "Asia",
                            TenantCountry = 1,
                            TenantName = "Tenant 4 (LifeStyles)"
                        });
                });

            modelBuilder.Entity("Main.Model.Identity.TenantInvitation", b =>
                {
                    b.Property<Guid>("InviteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AcceptedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiresOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvitedByUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("TenantContinent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TenantCountry")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenantRole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InviteId");

                    b.HasIndex("TenantId");

                    b.ToTable("TenantInvitations");
                });

            modelBuilder.Entity("Main.Model.Identity.TenantSmtpServer", b =>
                {
                    b.Property<int>("SmtpServerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SmtpServerId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Port")
                        .HasColumnType("int");

                    b.Property<string>("SmtpEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SmtpHostServer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenantContinent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TenantCountry")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SmtpServerId");

                    b.HasIndex("TenantId");

                    b.ToTable("TenantSmtpServers");
                });

            modelBuilder.Entity("Main.Model.Identity.TenantTheme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BodyBackgroundColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BodyColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ButtonBGBorderColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FontStack")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeaderColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LogoColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoRelativeFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MenuBackgroundColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MenuItemHoverBGColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MenuItemHoverColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenantContinent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TenantCountry")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("TenantThemes");
                });

            modelBuilder.Entity("Main.Model.Identity.TenantUserRole", b =>
                {
                    b.Property<int>("TenantUserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TenantUserRoleId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenantContinent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TenantCountry")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenantRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TenantUserRoleId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId");

                    b.ToTable("TenantUserRoles");

                    b.HasData(
                        new
                        {
                            TenantUserRoleId = 2,
                            IsActive = true,
                            TenantCountry = 1,
                            TenantId = new Guid("00000001-0000-0000-0000-000000000000"),
                            TenantRole = "Admin",
                            UserId = "00000004-0000-0000-0000-000000000000"
                        },
                        new
                        {
                            TenantUserRoleId = 3,
                            IsActive = true,
                            TenantCountry = 1,
                            TenantId = new Guid("00000001-0000-0000-0000-000000000000"),
                            TenantRole = "Manager",
                            UserId = "00000005-0000-0000-0000-000000000000"
                        },
                        new
                        {
                            TenantUserRoleId = 4,
                            IsActive = true,
                            TenantCountry = 1,
                            TenantId = new Guid("00000001-0000-0000-0000-000000000000"),
                            TenantRole = "Member",
                            UserId = "00000006-0000-0000-0000-000000000000"
                        },
                        new
                        {
                            TenantUserRoleId = 5,
                            IsActive = true,
                            TenantCountry = 1,
                            TenantId = new Guid("00000002-0000-0000-0000-000000000000"),
                            TenantRole = "Admin",
                            UserId = "00000007-0000-0000-0000-000000000000"
                        },
                        new
                        {
                            TenantUserRoleId = 6,
                            IsActive = true,
                            TenantCountry = 1,
                            TenantId = new Guid("00000002-0000-0000-0000-000000000000"),
                            TenantRole = "Manager",
                            UserId = "00000008-0000-0000-0000-000000000000"
                        },
                        new
                        {
                            TenantUserRoleId = 7,
                            IsActive = true,
                            TenantCountry = 1,
                            TenantId = new Guid("00000002-0000-0000-0000-000000000000"),
                            TenantRole = "Member",
                            UserId = "00000009-0000-0000-0000-000000000000"
                        },
                        new
                        {
                            TenantUserRoleId = 8,
                            IsActive = true,
                            TenantCountry = 1,
                            TenantId = new Guid("00000011-0000-0000-0000-000000000000"),
                            TenantRole = "Admin",
                            UserId = "0000000a-0000-0000-0000-000000000000"
                        },
                        new
                        {
                            TenantUserRoleId = 9,
                            IsActive = true,
                            TenantCountry = 1,
                            TenantId = new Guid("00000012-0000-0000-0000-000000000000"),
                            TenantRole = "Admin",
                            UserId = "0000000b-0000-0000-0000-000000000000"
                        });
                });

            modelBuilder.Entity("Main.Model.Identity.UserRefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("TenantContinent")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("TenantCountry")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId");

                    b.ToTable("ApplicationUserRefreshTokens");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "00000013-0000-0000-0000-000000000000",
                            Name = "GlobalAdmin",
                            NormalizedName = "GLOBALADMIN"
                        },
                        new
                        {
                            Id = "00000014-0000-0000-0000-000000000000",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "00000003-0000-0000-0000-000000000000",
                            RoleId = "00000013-0000-0000-0000-000000000000"
                        },
                        new
                        {
                            UserId = "00000004-0000-0000-0000-000000000000",
                            RoleId = "00000014-0000-0000-0000-000000000000"
                        },
                        new
                        {
                            UserId = "00000005-0000-0000-0000-000000000000",
                            RoleId = "00000014-0000-0000-0000-000000000000"
                        },
                        new
                        {
                            UserId = "00000006-0000-0000-0000-000000000000",
                            RoleId = "00000014-0000-0000-0000-000000000000"
                        },
                        new
                        {
                            UserId = "00000007-0000-0000-0000-000000000000",
                            RoleId = "00000014-0000-0000-0000-000000000000"
                        },
                        new
                        {
                            UserId = "00000008-0000-0000-0000-000000000000",
                            RoleId = "00000014-0000-0000-0000-000000000000"
                        },
                        new
                        {
                            UserId = "00000009-0000-0000-0000-000000000000",
                            RoleId = "00000014-0000-0000-0000-000000000000"
                        },
                        new
                        {
                            UserId = "0000000a-0000-0000-0000-000000000000",
                            RoleId = "00000014-0000-0000-0000-000000000000"
                        },
                        new
                        {
                            UserId = "0000000b-0000-0000-0000-000000000000",
                            RoleId = "00000014-0000-0000-0000-000000000000"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Main.Model.Identity.EmailOutboxMessage", b =>
                {
                    b.HasOne("Main.Model.Identity.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Main.Model.Identity.TenantInvitation", b =>
                {
                    b.HasOne("Main.Model.Identity.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Main.Model.Identity.TenantSmtpServer", b =>
                {
                    b.HasOne("Main.Model.Identity.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Main.Model.Identity.TenantTheme", b =>
                {
                    b.HasOne("Main.Model.Identity.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Main.Model.Identity.TenantUserRole", b =>
                {
                    b.HasOne("Main.Model.Identity.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Main.Model.Identity.ApplicationUser", "User")
                        .WithMany("TenantUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Main.Model.Identity.UserRefreshToken", b =>
                {
                    b.HasOne("Main.Model.Identity.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Main.Model.Identity.ApplicationUser", "User")
                        .WithMany("UserRefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Main.Model.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Main.Model.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Main.Model.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Main.Model.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Main.Model.Identity.ApplicationUser", b =>
                {
                    b.Navigation("TenantUsers");

                    b.Navigation("UserRefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
